/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package icroack.icroackadventures.view;

import icroack.icroackadventures.model.Audio;
import icroack.icroackadventures.model.Player;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;

/**
 *
 * @author FroggyTeam
 */
public class MenuPause extends javax.swing.JFrame {

    /**
     * Creates new form MenuPause
     */
    private Game game;
    public MenuPause(Game game) {
        this.setUndecorated(true);
        initComponents();
        this.setSize(330, 408);
        this.getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(0,0,0)));
        //this.setOpacity(0.9f);
        this.setLocationRelativeTo(null);
        this.game = game;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitlePause = new javax.swing.JLabel();
        buttonResume = new javax.swing.JLabel();
        buttonHome = new javax.swing.JLabel();
        buttonQuit = new javax.swing.JLabel();
        bgPause = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        TitlePause.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 36)); // NOI18N
        TitlePause.setForeground(new java.awt.Color(255, 255, 255));
        TitlePause.setText("PAUSE");
        getContentPane().add(TitlePause);
        TitlePause.setBounds(90, 80, 160, 80);

        buttonResume.setIcon(new javax.swing.ImageIcon("resource/buttonResume_r.png")); // NOI18N
        buttonResume.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonResumeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonResumeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonResumeMouseExited(evt);
            }
        });
        getContentPane().add(buttonResume);
        buttonResume.setBounds(90, 150, 150, 75);

        buttonHome.setIcon(new javax.swing.ImageIcon("resource/buttonHome_r.png")); // NOI18N
        buttonHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonHomeMouseExited(evt);
            }
        });
        getContentPane().add(buttonHome);
        buttonHome.setBounds(90, 230, 150, 75);

        buttonQuit.setIcon(new javax.swing.ImageIcon("resource/buttonQuit_r.png")); // NOI18N
        buttonQuit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonQuitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonQuitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonQuitMouseExited(evt);
            }
        });
        getContentPane().add(buttonQuit);
        buttonQuit.setBounds(90, 310, 150, 75);

        bgPause.setIcon(new javax.swing.ImageIcon("resource/Forest1.png"));
        getContentPane().add(bgPause);
        bgPause.setBounds(0, 0, 330, 408);

        pack();
    }

    private void buttonResumeMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        ImageIcon bResClick = new ImageIcon("resource/buttonResume3_r.png");
        buttonResume.setIcon(bResClick);
        this.dispose();
        Game.tt.resume();
    }

    private void buttonHomeMouseClicked(java.awt.event.MouseEvent evt) {

        this.dispose();
        game.dispose();
        game.tt.stop();
        game.tt.setM(0);
        game.tt.setS(0);
        Audio.stop();
        Home h;

        try {
            h = new Home();
            if (Player.isAdmin) Home.btnAdmin.setVisible(true);
            else Home.btnAdmin.setVisible(false);
            h.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(MenuPause.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    private void buttonQuitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonQuitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_buttonQuitMouseClicked

    private void buttonResumeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonResumeMouseEntered
        // TODO add your handling code here:
        ImageIcon bResEnter = new ImageIcon("resource/buttonResume2_r.png");
        buttonResume.setIcon(bResEnter);
    }//GEN-LAST:event_buttonResumeMouseEntered

    private void buttonResumeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonResumeMouseExited
        // TODO add your handling code here:
        ImageIcon bResEx = new ImageIcon("resource/buttonResume_r.png");
        buttonResume.setIcon(bResEx);
    }//GEN-LAST:event_buttonResumeMouseExited

    private void buttonHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHomeMouseEntered
        // TODO add your handling code here:
        ImageIcon bHomEnter = new ImageIcon("resource/buttonHome2_r.png");
        buttonHome.setIcon(bHomEnter);
    }//GEN-LAST:event_buttonHomeMouseEntered

    private void buttonHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHomeMouseExited
        // TODO add your handling code here:
        ImageIcon bHomEx = new ImageIcon("resource/buttonHome_r.png");
        buttonHome.setIcon(bHomEx);
    }//GEN-LAST:event_buttonHomeMouseExited

    private void buttonQuitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonQuitMouseEntered
        // TODO add your handling code here:
        ImageIcon bQuitEnter = new ImageIcon("resource/buttonQuit2_r.png");
        buttonQuit.setIcon(bQuitEnter);
    }//GEN-LAST:event_buttonQuitMouseEntered

    private void buttonQuitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonQuitMouseExited
        // TODO add your handling code here:
        ImageIcon bQuitEx = new ImageIcon("resource/buttonQuit_r.png");
        buttonQuit.setIcon(bQuitEx);
    }//GEN-LAST:event_buttonQuitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPause.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPause.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPause.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPause.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPause().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TitlePause;
    private javax.swing.JLabel bgPause;
    private javax.swing.JLabel buttonHome;
    private javax.swing.JLabel buttonQuit;
    private javax.swing.JLabel buttonResume;
    // End of variables declaration//GEN-END:variables
}
